fix: try to remode a plugin or jar before downloading it during initC…
gravitee-io/helm-charts pull request #204
Opened 2022-01-17 22:23 UTC by leleueri

…ontainer execution

fixes gravitee-io/issues#6887

2022-01-17 22:33 UTC, brasseld requested changes
APIM unit tests are not working anymore
`helm unittest -3 -f 'tests/**/*.yaml' .`

2022-01-28 07:12 UTC, jgiovaresco approved these changes

2022-01-28 07:12 UTC, jgiovaresco commented on am/templates/api/api-configmap.yaml
> +            <logger name="com.mongodb" level="DEBUG" />
Is it wanted to activate DEBUG log?

2022-01-31 07:52 UTC, leleueri commented on am/templates/api/api-configmap.yaml
> +            <logger name="com.mongodb" level="DEBUG" />
No, thank for pointing this.

2022-02-04 00:05 UTC, brasseld approved these changes

2022-02-04 07:05 UTC, jgiovaresco approved these changes

2022-02-07 08:20 UTC, merged