Adding an option to disable the newsletter popup in apim3
gravitee-io/helm-charts pull request #209
Opened 2022-01-31 09:48 UTC by oyviaase

**Issue**

https://github.com/gravitee-io/issues/issues/7027
**Description**

Added a value to enable/disable the popup asking a new user to sign up to the gravitee news-letter

2022-01-31 11:08 UTC, phiz71 commented on apim/3.x/README.md
> +| `api.ratingEnabled`                                   | Whether to enable newsletter sign up feature
```suggestion
| `api.newsletterEnabled`                                   | Whether to enable newsletter sign up feature                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | `true`                                                                                                                                                      |
```

2022-01-31 11:09 UTC, phiz71 requested changes
LGTM, except for the little copy/paste issue ;) 
@brasseld wdyt ?

2022-01-31 12:05 UTC, brasseld commented
LGTM as well 👍

2022-01-31 19:39 UTC, brasseld approved these changes

2022-03-02 10:38 UTC, gaetanmaisse approved these changes

2022-03-02 10:40 UTC, merged