feat: Add support for managed ServiceAccounts name provided by user
gravitee-io/helm-charts pull request #253
Opened 2022-05-05 12:42 UTC by kamiiiel

**Issue**

https://github.com/gravitee-io/issues/issues/XXXXX

**Description**

A small description of what you did in that PR.

**Additional context**

2022-05-06 06:28 UTC, jgiovaresco approved these changes

2022-05-06 07:12 UTC, leleueri requested changes
Can you please add Unittest for AM and provide documentation about different options ?

2022-05-06 13:49 UTC, brasseld approved these changes

2022-05-09 10:30 UTC, kamiiiel commented
> Can you please add Unittest for AM and provide documentation about different options ?

I added the test for AM as well and regarding the documentation, maybe it is better to put this in a page or something, this is a settings similar for all products. What do you think @brasseld ?

2022-05-12 08:51 UTC, brasseld commented
> > Can you please add Unittest for AM and provide documentation about different options ?
> 
> I added the test for AM as well and regarding the documentation, maybe it is better to put this in a page or something, this is a settings similar for all products. What do you think @brasseld ?

Good point @kamiiiel I'm just wondering what is the best place for this.

2022-05-16 14:17 UTC, merged