doc(am): explain how to use ConfigMap & Secrets to initialize GIO set…
gravitee-io/helm-charts pull request #256
Opened 2022-05-10 10:02 UTC by leleueri

https://github.com/gravitee-io/issues/issues/7630

2022-05-12 10:06 UTC, farmborough requested changes

2022-05-12 10:06 UTC, farmborough commented on am/README.adoc
> +To use this feature, you have to create the ServiceAccount that allow AM to connect to the Kubernetes API (the helm chart should do it by default) and then  you simply have to define you application
```suggestion
To use this feature, you have to create the ServiceAccount that allows AM to connect to the Kubernetes API (the helm chart should do it by default) and then you simply have to define your application settings like this:
```

2022-05-12 10:06 UTC, farmborough commented on am/README.adoc
> +Here is an example for the mongodb uri initialized from the `mongo` secret deployed in to the `default` namespace:
```suggestion
Here is an example for the mongodb uri initialized from the `mongo` secret deployed in the `default` namespace:
```

2022-05-12 10:06 UTC, farmborough commented on am/README.md
> +To use this feature, you have to create the ServiceAccount that allow AM to connect to the Kubernetes API (the helm chart should do it by default) and then  you simply have to define you application
```suggestion
To use this feature, you have to create the ServiceAccount that allows AM to connect to the Kubernetes API (the helm chart should do it by default) and then you simply have to define your application settings like this:
```

2022-05-12 10:06 UTC, farmborough commented on am/README.md
> +Here is an example for the mongodb uri initialized from the `mongo` secret deployed in to the `default` namespace:
```suggestion
Here is an example for the mongodb uri initialized from the `mongo` secret deployed in the `default` namespace:
```

2022-05-17 09:33 UTC, remisultan approved these changes

2022-05-17 09:58 UTC, gaetanmaisse approved these changes

2022-05-19 08:11 UTC, merged