Add a startup probe on m-api
gravitee-io/helm-charts pull request #294
Opened 2022-08-24 07:11 UTC by NicolasGeraud

**Description**

Depending on the time to execute java upgraders during a version upgrade, we encountered issues when k8s restarted the pod even if the upgrade was not finished.
The "workaround" is to add a startup probe to accept a long initial startup.

2022-08-24 12:47 UTC, brasseld requested changes
Can this be replicated to all charts, and add missing uni tests ?

2022-08-29 09:29 UTC, NicolasGeraud commented
unit tests added.
The startup latency is due to java upgrader so I don't think it makes sense to add a startup probe to other components.

2022-08-31 20:06 UTC, brasseld approved these changes

2022-09-01 06:29 UTC, gaetanmaisse approved these changes

2022-09-01 06:29 UTC, gaetanmaisse commented
⚠️ We need to update the version and changelog before releasing this

2022-09-01 06:59 UTC, gaetanmaisse commented
We will work on https://github.com/gravitee-io/helm-charts/pull/296 today and merge then release them both

2022-09-02 09:36 UTC, merged