fix(apim): error port name too long
gravitee-io/helm-charts pull request #296
Opened 2022-08-25 14:32 UTC by ThibaudAV

**Issue**

Next to https://github.com/gravitee-io/helm-charts/pull/292

**Description**

Merge in temp Branche to validate CI and add some tests

**Additional context**

2022-09-02 08:18 UTC, mariano-fernandez approved these changes

2022-09-02 09:10 UTC, leleueri reviewed
Can you add unit tests on AM please and add an entry into the Changelogs + Chart.yml to inform about the change ?
In addition, name limitation look to be restricted to the POD spec, not in the sevice spec, but for consistency against products, I'm ok to apply it on AM too.

2022-09-02 09:28 UTC, mariano-fernandez commented
> Can you add unit tests on AM please and add an entry into the Changelogs + Chart.yml to inform about the change ?

There is already a unit-test for cockpit, but can we get the `changelog + chart.hml` part ? 😬

2022-09-02 14:56 UTC, ThibaudAV commented
@leleueri I didn't really find any doc on this subject.
But if it's only for pods then I leave as before on services ? or limit to 63
And add limit only when needed

2022-09-09 07:21 UTC, remisultan commented
ditto all of the above for AE with `Unit tests + Charts.yml`  change

2022-09-09 07:22 UTC, leleueri requested changes

2022-09-09 07:22 UTC, leleueri commented on am/templates/gateway/gateway-service.yaml
> +      name: {{ .Values.gateway.name | trunc 15 | trimSuffix "-" }}
On Service resource, names are limited to 63 chars

2022-09-09 07:22 UTC, leleueri commented on am/templates/gateway/gateway-service.yaml
> +      name: {{ printf "%s-%s" (.Values.gateway.name | trunc 5 | trimSuffix "-") "technical" }}
On Service resource, names are limited to 63 chars so here the trunc should be done at 53 chars in order to be able to append "-technical"

2022-09-09 07:22 UTC, leleueri commented on am/templates/api/api-service.yaml
> +      name: {{ .Values.api.name | trunc 15 | trimSuffix "-" }}
On Service resource, names are limited to 63 chars

2022-09-09 07:22 UTC, leleueri commented on am/templates/api/api-service.yaml
> +      name: {{ printf "%s-%s" (.Values.api.name | trunc 5 | trimSuffix "-") "technical" }}
On Service resource, names are limited to 63 chars so here the trunc should be done at 53 chars in order to be able to append "-technical"

2022-09-09 07:22 UTC, leleueri commented on am/templates/ui/ui-service.yaml
> +      name: {{ .Values.ui.name | trunc 15 | trimSuffix "-" }}
On Service resource, names are limited to 63 chars

2022-09-12 12:00 UTC, ThibaudAV commented
Following discussion with @leleueri . The limit is kept at 63 for services and 15 deployment. as the one imposed by k8s

2022-09-12 12:03 UTC, leleueri approved these changes

2022-09-12 17:26 UTC, gaetanmaisse approved these changes

2022-09-12 17:27 UTC, merged