Enable or disable elasticsearch from values
gravitee-io/helm-charts pull request #70
Opened 2020-10-21 17:52 UTC by ydbondt

And remove trailing spaces (default by IDE)

2020-10-22 07:09 UTC, ydbondt commented on apim/3.x/templates/api/api-configmap.yaml
> +        enabled: {{ .Values.es.enabled }}
Apparently this can't be disabled in api config ?

2020-11-10 08:05 UTC, brasseld commented on apim/3.x/templates/api/api-configmap.yaml
> +        enabled: {{ .Values.es.enabled }}
Hi @ydbondt 

For now, analytics can't be disable for mgmt-api.
You don't want analytics ?

2020-11-10 08:06 UTC, brasseld requested changes
Looking for feedback

2021-02-16 16:25 UTC, ydbondt commented on apim/3.x/templates/api/api-configmap.yaml
> +        enabled: {{ .Values.es.enabled }}
It is not that we don't want analytics, but when we do a proof of concept we don't want to be forced to install a rather big component like elasticsearch.

2021-06-30 07:42 UTC, arne-heil commented
Please implement this feature. We could really use a minimal footprint with at least Elasticsearch as an optional choice. Thanks in advance :smile:

2021-06-30 07:54 UTC, brasseld commented
> Please implement this feature. We could really use a minimal footprint with at least Elasticsearch as an optional choice. Thanks in advance 😄

Hi @arne-heil 

Currently, Elasticsearch is an optional dependency for the API Gateway (you could rely on other reporters like TCP, file, ...).
But it's still not at the Management API level.

Why disabling ES would need a minimal footprint (for the Management API) ?

2021-06-30 08:10 UTC, arne-heil commented
> > Please implement this feature. We could really use a minimal footprint with at least Elasticsearch as an optional choice. Thanks in advance smile
> 
> Hi @arne-heil
> 
> Currently, Elasticsearch is an optional dependency for the API Gateway (you could rely on other reporters like TCP, file, ...).
> But it's still not at the Management API level.
> 
> Why disabling ES would need a minimal footprint (for the Management API) ?

We would like to enable and disable ES when needed. Otherwise we have to maintain a ES instance only for Gravitee usage and/or disable the Management API after setting up and deploying our API.

2021-06-30 08:13 UTC, brasseld commented
> We would like to enable and disable ES when needed. Otherwise we have to maintain a ES instance only for Gravitee usage and/or disable the Management API after setting up and deploying our API.

Meaning that you're happy not having any kind of analytics from Gravitee, right?

2021-06-30 08:21 UTC, arne-heil commented
> > We would like to enable and disable ES when needed. Otherwise we have to maintain a ES instance only for Gravitee usage and/or disable the Management API after setting up and deploying our API.
> 
> Meaning that you're happy not having any kind of analytics from Gravitee, right?

In general, yes. We don't have any complains about Gravitee in combination with our API  and analytics would be a nice optional feature for us.

2021-09-08 19:18 UTC, closed without merging

2021-09-08 19:19 UTC, ydbondt commented
If there is any intention to apply this, you can reopen the pull request.